### ISSUE TITLE
Datetime field with datepicker sends wrongly formatted datetime to the database (MySQL)

### ISSUE THREAD

**Issue by megant** [MWSimple/AdminCrudBundle#10]
Datetime field with datepicker sends wrongly formatted datetime to the database (MySQL).

**Comment by gonzakpo** [comment]
Could you explain better ... I had no problems.

**Comment by megant** [comment]
On Symfony 2.6.*

With this entity:

http://pastebin.com/m8Vx6h0j

and with this entity config:

http://pastebin.com/sJ8Akg0s

when I click on "Save" button of the add new item page, it says:

"This value is not valid."

**Comment by gonzakpo** [comment]
not probe with yml, use entity annotations and tell me if it works

**Comment by megant** [comment]
The same. Does not depend on configuration type.

**Comment by megant** [comment]
By the way (i know, its a bit offtipic, but) is there any special I would have to see on /admin in addition to "inicio" and "Administrator"? For example a basic admin menu or anything.

**Comment by gonzakpo** [comment]
Tiene un menu que podes configurarlo.
It has a menu you can configure

**Comment by megant** [comment]
Did you find anything?

**Comment by gonzakpo** [comment]
you have form type: ->add('fechanac', 'bootstrapdatetime') ??

**Comment by megant** [comment]
->add('publishedAt', 'bootstrapdatetime', array(
                'required'   => true,
                'label'      => 'Publishedat',
                'label_attr' => array(
                    'class' => 'col-lg-2 col-md-2 col-sm-2',
                ),
                'widget_type' => 'both',
            ))

**Comment by gonzakpo** [comment]
later I make some tests

**Comment by gonzakpo** [comment]
Envie cambios!

**Comment by gonzakpo** [comment]
Use php intl
