### ISSUE TITLE
config.yml entity 

### ISSUE THREAD

**Issue by maxshtefec** [MWSimple/AdminCrudBundle#103]
comento la config index para que dentro de la vista new desaparezca el botón "volver a la lista" y el icono superior derecho. Al regresar al listado en index por url, me arroja un error el filter form, linea 231 defaultController no encuentra la misma ruta que he comentado,

Solución: Agregue la misma función createFilterForm a mi controlador indicándole yo mismo la ruta. y el import del botón "submit"

use Symfony\Component\Form\Extension\Core\Type\SubmitType;

**Comment by maxshtefec** [comment]
otra solución es sobreescribir la vista new para quitar "2 botones"

**Comment by gonzaloalonsod** [comment]
al comentar se quita la funcion completa no solo los botones
