### ISSUE TITLE
KNP menu does not render anything

### ISSUE THREAD

**Issue by megant** [MWSimple/AdminCrudBundle#11]
The line {{ knp_menu_render('MWSimpleAdminCrudBundle:Builder:adminMenu') }} in vendor/mwsimple/admin-crud/MWSimple/Bundle/AdminCrudBundle/Resources/views/layout.html.twig does not render anything. Did I miss some configuration entry?

**Comment by gonzakpo** [comment]
got this entry:

mw_simple_admin_crud:
    menu:
        child: { name: inicio, url: mws_admin_crud_menu }
        #child2: { name: seccion, url: admin_seccion }

**Comment by megant** [comment]
False alarm. It worx. A recursive solution would be fine. ;)

**Comment by gonzakpo** [comment]
: D If I do not want to do that hard.
