### ISSUE TITLE
Unable to generate a URL for the named route "..."

### ISSUE THREAD

**Issue by priverop** [MWSimple/AdminCrudBundle#112]
Hello, I just did a new fresh installation.

I created one Entity, crud generator and now I've got this:
_Unable to generate a URL for the named route "cliente" as such route does not exist._

`ymfony\Component\Routing\Exception\RouteNotFoundException:
Unable to generate a URL for the named route "cliente" as such route does not exist.

  at var/cache/dev/appDevDebugProjectContainerUrlGenerator.php:51
  at appDevDebugProjectContainerUrlGenerator->generate('cliente', array(), 1)
     (var/cache/dev/classes.php:1832)
  at Symfony\Component\Routing\Router->generate('cliente', array(), 1)
     (vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Controller/ControllerTrait.php:85)
  at Symfony\Bundle\FrameworkBundle\Controller\Controller->generateUrl('cliente')
     (vendor/mwsimple/admin-crud/Controller/DefaultController.php:343)
  at MWSimple\Bundle\AdminCrudBundle\Controller\DefaultController->createFilterForm()
     (vendor/mwsimple/admin-crud/Controller/DefaultController.php:297)
  at MWSimple\Bundle\AdminCrudBundle\Controller\DefaultController->filter(object(Request))
     (vendor/mwsimple/admin-crud/Controller/DefaultController.php:45)
  at MWSimple\Bundle\AdminCrudBundle\Controller\DefaultController->indexAction(object(Request))
     (src/AppBundle/Controller/ClienteController.php:33)
  at AppBundle\Controller\ClienteController->indexAction(object(Request))
  at call_user_func_array(array(object(ClienteController), 'indexAction'), array(object(Request)))
     (var/cache/dev/classes.php:4328)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), 1)
     (var/cache/dev/classes.php:4283)
  at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), 1, true)
     (vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:202)
  at Symfony\Component\HttpKernel\Kernel->handle(object(Request))
     (web/app_dev.php:29)
  at require('/Applications/XAMPP/xamppfiles/htdocs/_symfonybuilders/mwsimple/web/app_dev.php')
     (vendor/symfony/symfony/src/Symfony/Bundle/WebServerBundle/Resources/router.php:42)`

My routing.yml:

```
app_cliente:
    resource: "@AppBundle/Resources/config/routing/cliente.yml"
    prefix:   /cliente
```

I can't get /admin functioning either:

`Unable to find template "MWSimpleAdminCrudBundle:Backend:index.html.twig" (looked into: /---/mwsimple/vendor/knplabs/knp-menu/src/Knp/Menu/Resources/views, /---/mwsimple/app/Resources/views, /---/mwsimple/vendor/symfony/symfony/src/Symfony/Bridge/Twig/Resources/views/Form).`

I'm using Symfony 3.4.2, PHP 5.6.30 on Mac OS X.

**Comment by camuschino** [comment]
Can you share your controller generated by Admincrud? Did you generate a new controller to handle your Cliente entity?


El 25 dic. 2017 4:39 PM, Pablo Rivero <notifications@github.com> escribió:

Hello, I just did a new fresh installation.

I created one Entity, crud generator and now I've got this:
Unable to generate a URL for the named route "cliente" as such route does not exist.

`ymfony\Component\Routing\Exception\RouteNotFoundException:
Unable to generate a URL for the named route "cliente" as such route does not exist.

at var/cache/dev/appDevDebugProjectContainerUrlGenerator.php:51
at appDevDebugProjectContainerUrlGenerator->generate('cliente', array(), 1)
(var/cache/dev/classes.php:1832)
at Symfony\Component\Routing\Router->generate('cliente', array(), 1)
(vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Controller/ControllerTrait.php:85)
at Symfony\Bundle\FrameworkBundle\Controller\Controller->generateUrl('cliente')
(vendor/mwsimple/admin-crud/Controller/DefaultController.php:343)
at MWSimple\Bundle\AdminCrudBundle\Controller\DefaultController->createFilterForm()
(vendor/mwsimple/admin-crud/Controller/DefaultController.php:297)
at MWSimple\Bundle\AdminCrudBundle\Controller\DefaultController->filter(object(Request))
(vendor/mwsimple/admin-crud/Controller/DefaultController.php:45)
at MWSimple\Bundle\AdminCrudBundle\Controller\DefaultController->indexAction(object(Request))
(src/AppBundle/Controller/ClienteController.php:33)
at AppBundle\Controller\ClienteController->indexAction(object(Request))
at call_user_func_array(array(object(ClienteController), 'indexAction'), array(object(Request)))
(var/cache/dev/classes.php:4328)
at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), 1)
(var/cache/dev/classes.php:4283)
at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), 1, true)
(vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:202)
at Symfony\Component\HttpKernel\Kernel->handle(object(Request))
(web/app_dev.php:29)
at require('/Applications/XAMPP/xamppfiles/htdocs/_symfonybuilders/mwsimple/web/app_dev.php')
(vendor/symfony/symfony/src/Symfony/Bundle/WebServerBundle/Resources/router.php:42)`

My routing.yml:

app_cliente:
    resource: "@AppBundle/Resources/config/routing/cliente.yml"
    prefix:   /cliente


I can't get /admin functioning either:

Unable to find template "MWSimpleAdminCrudBundle:Backend:index.html.twig" (looked into: /---/mwsimple/vendor/knplabs/knp-menu/src/Knp/Menu/Resources/views, /---/mwsimple/app/Resources/views, /---/mwsimple/vendor/symfony/symfony/src/Symfony/Bridge/Twig/Resources/views/Form).

I'm using Symfony 3.4.2, PHP 5.6.30 on Mac OS X.

**Comment by gonzaloalonsod** [comment]
AppBundle/Resources/config/routing/cliente.yml
the content of the file?

**Comment by priverop** [comment]
**AppBundle/Resources/config/routing/cliente.yml**
```
cliente_index:
    path:     /
    defaults: { _controller: "AppBundle:Cliente:index" }
    methods:  GET

cliente_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Cliente:show" }
    methods:  GET

cliente_new:
    path:     /new
    defaults: { _controller: "AppBundle:Cliente:new" }
    methods:  [GET, POST]

cliente_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Cliente:edit" }
    methods:  [GET, POST]

cliente_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Cliente:delete" }
    methods:  DELETE
```

ClienteController.php (generated by AdminCrud):

```
<?php

namespace AppBundle\Controller;

use AppBundle\Entity\Cliente;
use AppBundle\Form\ClienteType;
use MWSimple\Bundle\AdminCrudBundle\Controller\DefaultController as Controller;
use Symfony\Component\HttpFoundation\Request;
use AppBundle\Form\ClienteFilterType;


/**
 * Cliente controller.
 * @author Nombre Apellido <name@gmail.com>
 *
 */
class ClienteController extends Controller
{
    /**
     * Configuration file.
     */
    protected $config = [
        'yml' => 'AppBundle/Resources/config/Cliente.yml',
    ];

    /**
     * Lists all Cliente entities.
     *
     */
    public function indexAction(Request $request)
    {
        $this->config['filterType'] = ClienteFilterType::class;
        $response = parent::indexAction($request);

        return $this->render('AppBundle:Cliente:index.html.twig', [
            'entities'   => $pagination,
            'filterForm' => $filterForm->createView(),
        ]);
    }

    /**
     * Creates a new Cliente entity.
     *
     */
    public function createAction(Request $request)
    {
        $this->config['newType'] = ClienteType::class;
        $response = parent::createAction($request);

        return $response;
    }

    /**
     * Displays a form to create a new Cliente entity.
     *
     */
    public function newAction()
    {
        $this->config['newType'] = ClienteType::class;
        $response = parent::newAction();

        return $response;
    }

    /**
     * Finds and displays a Cliente entity.
     *
     */
    public function showAction($id)
    {
        $response = parent::showAction($id);

        return $response;
    }

    /**
     * Displays a form to edit an existing Cliente entity.
     *
     */
    public function editAction($id)
    {
        $this->config['editType'] = ClienteType::class;
        $response = parent::editAction($id);

        return $response;
    }

    /**
     * Edits an existing Cliente entity.
     *
     */
    public function updateAction(Request $request, $id)
    {
        $this->config['editType'] = ClienteType::class;
        $response = parent::updateAction($request, $id);

        return $response;
    }

    /**
     * Deletes a Cliente entity.
     *
     */
    public function deleteAction(Request $request, $id)
    {
        $response = parent::deleteAction($request, $id);

        return $response;
    }

    /**
     * Exporter Cliente.
     *
     */
    public function getExporter($format)
    {
        $response = parent::exportCsvAction($format);

        return $response;
    }
}
```

No, I haven't generated any more controllers. I just did doctrine:generate:entitity and then mwsimple:generate:admincrud.

**Comment by gonzakpo** [comment]
We are working on it

**Comment by gonzaloalonsod** [comment]
We are working on it. **You should use php7**

**Comment by priverop** [comment]
If PHP7 is a must, I think it should be specified in the documentation :)

Thank you for your time.
Regards.

**Comment by gonzaloalonsod** [comment]
If equally to use the bundle try with sf 3.3.
In itself 3.4.2 still does not work correctly.
