### ISSUE TITLE
PHP Fatal error:  Allowed memory size of 1610612736 bytes exhausted 

### ISSUE THREAD

**Issue by flik** [MWSimple/AdminCrudBundle#113]
$ composer require mwsimple/admin-crud
Using version ^3.3 for mwsimple/admin-crud
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)

Failed to decode response: zlib_decode(): data error
Retrying with degraded mode, check https://getcomposer.org/doc/articles/troubleshooting.md#degraded-mode for more info
PHP Fatal error:  Allowed memory size of 1610612736 bytes exhausted (tried to allocate 4096 bytes) in phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Package/Loader/ArrayLoader.php on line 241

Fatal error: Allowed memory size of 1610612736 bytes exhausted (tried to allocate 4096 bytes) in phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Package/Loader/ArrayLoader.php on line 241

Check https://getcomposer.org/doc/articles/troubleshooting.md#memory-limit-errors for more info on how to handle out of memory errors.

**Comment by gonzaloalonsod** [comment]
PHP 7 ?

Composer solution: php -d memory_limit=-1 composer.phar

**Comment by flik** [comment]
php -d memory_limit=-1 composer require mwsimple/admin-crud
Could not open input file: composer

**Comment by flik** [comment]
I am using windows

**Comment by gonzaloalonsod** [comment]
use PHP 7 ?

example composer.phar in windows: https://www.youtube.com/watch?v=mXNaTCuMfKw

**Comment by flik** [comment]
yes. PHP 7

**Comment by flik** [comment]
ok. thanks
