### ISSUE TITLE
Mejorar documentacion

### ISSUE THREAD

**Issue by gonzaloalonsod** [MWSimple/AdminCrudBundle#57]
Agregar en Español e Ingles

**Comment by YulianD** [comment]
**Los felicito de verdad**, me parece excelente este proyecto, ya que esta desarrollado por una comunidad hispana, yo aun aprendo symfony, espero algún día poder colaborar aunque sea con la Wiki, nuevamente felicitaciones!

**Comment by gonzaloalonsod** [comment]
Buenas! **Muchas gracias** esperemos puedas colaborar en algun momento, dale una mirada al bundle y a los demas bundles que se desarrollan, es una buena forma de aprender.
Saludos!!!
https://groups.google.com/d/forum/symfony-2-argentina
